
###
//get user data
GET http://localhost:5000/api/auth/me
Authorization: Bearer {{$aadToken}}

###
//login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "user123"
}

###
//register user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "user",
    "email": "user@gmail.com",
    "password": "user123"
}